#!/bin/bash
# Make CSD for Spider text-to-SQL using GPT 5.4 generation and Qwen 7B evaluation.
# Usage: bash synthesis/shell/spider_gpt54_qwen7b.sh [extra generate_csd args]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAX_TOKENS="${MAX_TOKENS:-1000}"
export CSD_SPIDER_FORCE_SINGLE_SQL_SPAN="${CSD_SPIDER_FORCE_SINGLE_SQL_SPAN:-1}"
export CSD_SPIDER_FORCE_SPAN_AT_START="${CSD_SPIDER_FORCE_SPAN_AT_START:-1}"
export CSD_ALLOW_LEADING_DELIMITER="${CSD_ALLOW_LEADING_DELIMITER:-1}"
export CSD_DISALLOW_CONSTRAINED_WHITESPACE="${CSD_DISALLOW_CONSTRAINED_WHITESPACE:-1}"
export CSD_FORCE_CLOSE_ON_COMPLETE="${CSD_FORCE_CLOSE_ON_COMPLETE:-1}"
export CSD_FORCE_CLOSE_MIN_SPAN_TOKENS="${CSD_FORCE_CLOSE_MIN_SPAN_TOKENS:-6}"
export CSD_SPIDER_EVAL_RANDOM_SAMPLE="${CSD_SPIDER_EVAL_RANDOM_SAMPLE:-0}"
export CSD_CONSTRAINED_SAMPLING="${CSD_CONSTRAINED_SAMPLING:-0}"
export CSD_CONSTRAINED_TEMPERATURE="${CSD_CONSTRAINED_TEMPERATURE:-0.35}"
export CSD_CONSTRAINED_TOP_P="${CSD_CONSTRAINED_TOP_P:-0.9}"
source "$SCRIPT_DIR/common.sh"
csd_run_preset spider "Spider SQL" "$@"
