// CSD_RATIONALE_BEGIN
// The previous attempt timed out during Dafny verification due to complex loop
// invariants and multiple phases. The fix is to simplify the structure to reduce
// verification complexity while preserving the same runtime behavior.
//
// Key simplifications:
// 1. Merge minInnerTokens phase into the main constrained loop using a counter.
// 2. Reduce the number of separate while loops.
// 3. Use a single unified main loop with ManagedStep to avoid complex invariant proofs.
// 4. Fall back to CloseSpanWithinBudget at the end for safety.
//
// Strategy:
// - Phase 1: Use UnconstrainedChunk to find "<<" in free text (up to 75% budget)
// - Phase 2: Inside span, use ConstrainedStep for up to innerStepLimit steps,
//   but only attempt CloseSpanIfComplete after minInnerTokens tokens are generated
// - Phase 3: CloseSpanWithinBudget for remaining budget if span still open
// - Phase 4: If no span seen, force OpenConstrainedSpan + ConstrainedStep loop
// - Phase 5: Final CloseSpanWithinBudget
// CSD_RATIONALE_END
// CSD_PROOF_SKETCH_BEGIN
// parser_validity:
//   Phase 1 (UnconstrainedChunk): insideConstrainedOut stays false until stoppedOnOpen,
//     then EnterObservedConstrainedSpan sets currentConstrainedOut := [] which satisfies
//     IsValidPrefix([]) by precondition parser.IsValidPrefix([]).
//   Phase 2 (constrained loop): ConstrainedStep returns a parser-valid token;
//     AppendConstrainedToken postcondition ensures IsValidPrefix(currentConstrainedOut)
//     is preserved. CloseSpanIfComplete either closes (vacuous) or is no-op.
//   Phase 3 (CloseSpanWithinBudget): postcondition guarantees
//     insideConstrainedOut ==> parser.IsValidPrefix(currentConstrainedOut).
//   Phase 4 (OpenConstrainedSpan + loop): OpenConstrainedSpan sets currentConstrainedOut := []
//     (valid). Same ConstrainedStep + AppendConstrainedToken argument as Phase 2.
//   Phase 5 (CloseSpanWithinBudget): same as Phase 3.
//
// progress (|generated| <= |generatedPrefix| + steps):
//   Phase 1: UnconstrainedChunk adds stepsUsed to steps and grows generated by at most
//     stepsUsed tokens. EnterObservedConstrainedSpan adds 0.
//   Phase 2: Each iteration increments steps by 1. ConstrainedStep adds 0 to generated
//     (token not yet appended). AppendConstrainedToken appends 1 token, so
//     |generated| grows by at most 1 = steps increment. CloseSpanIfComplete
//     increments steps by 1 and appends at most 1 token (the ">>" delimiter).
//   Phase 3: CloseSpanWithinBudget postcondition:
//     |generatedOut| <= |generated| + spanBudget = |generated| + (maxSteps - steps_before),
//     and steps := steps + spanBudget <= maxSteps. Invariant preserved.
//   Phase 4: OpenConstrainedSpan appends 1 token ("<<"), steps += 1. Each loop
//     iteration: steps += 1, |generated| grows by at most 1.
//   Phase 5: Same as Phase 3.
// CSD_PROOF_SKETCH_END

generated := generatedPrefix;
insideConstrainedOut := insideConstrained;
currentConstrainedOut := currentConstrained;
cost := 0;

if maxSteps == 0 {
  return;
}

var guidance: string := "Solve step by step. At the very end, write exactly: The answer is <<EXPR>> where EXPR is a full arithmetic expression using only the symbolic variable names from the problem (like n, price, rate, count, etc.), numbers, and operators +, -, *, /, (, ). The expression must show the complete computation, not just a single number. No LaTeX, no {}, no **, no $.";
helpers.AppendTaskGuidance(lm, guidance);

var steps: nat := 0;
var hasCompletedSpan: bool := false;
var chunkSize: nat := 40;
var minInnerTokens: nat := 6;

var phase1Limit: nat := (maxSteps * 75) / 100;
if phase1Limit == 0 {
  phase1Limit := 1;
}

// Phase 1: Unconstrained generation watching for "<<" opening delimiter
while steps < phase1Limit && !insideConstrainedOut && !hasCompletedSpan
  invariant 0 <= steps <= maxSteps
  invariant lm.ValidTokensIdsLogits()
  invariant !insideConstrainedOut ==> currentConstrainedOut == []
  invariant insideConstrainedOut ==> parser.IsValidPrefix(currentConstrainedOut)
  invariant insideConstrainedOut ==> |currentConstrainedOut| <= |generated|
  invariant |generated| <= |generatedPrefix| + steps
  decreases phase1Limit - steps
{
  var actualChunk := chunkSize;
  if steps + actualChunk > phase1Limit {
    actualChunk := phase1Limit - steps;
  }
  if actualChunk == 0 {
    break;
  }
  var cg, stoppedOnOpen, stoppedOnEos, stepsUsed := helpers.UnconstrainedChunk(lm, prompt, generated, actualChunk, "<<", eosToken);
  generated := cg;
  steps := steps + stepsUsed;
  if stoppedOnEos {
    break;
  }
  if stoppedOnOpen {
    var eg, ei, ec := helpers.EnterObservedConstrainedSpan(lm, generated);
    generated := eg;
    insideConstrainedOut := ei;
    currentConstrainedOut := ec;
  }
}

// Phase 2: Constrained generation with minInnerTokens guard before CloseSpanIfComplete
var innerStepLimit: nat := 120;
var innerSteps: nat := 0;
var innerTokenCount: nat := 0;

while insideConstrainedOut && !hasCompletedSpan && steps < maxSteps && innerSteps < innerStepLimit
  invariant 0 <= steps <= maxSteps
  invariant lm.ValidTokensIdsLogits()
  invariant !insideConstrainedOut ==> currentConstrainedOut == []
  invariant insideConstrainedOut ==> parser.IsValidPrefix(currentConstrainedOut)
  invariant insideConstrainedOut ==> |currentConstrainedOut| <= |generated|
  invariant |generated| <= |generatedPrefix| + steps
  decreases (maxSteps - steps) + (innerStepLimit - innerSteps)
{
  if innerTokenCount >= minInnerTokens {
    var cg, ci, cc, closed := helpers.CloseSpanIfComplete(lm, parser, generated, currentConstrainedOut);
    if closed {
      generated := cg;
      insideConstrainedOut := ci;
      currentConstrainedOut := cc;
      steps := steps + 1;
      hasCompletedSpan := true;
      break;
    }
  }
  var constrainedPrompt := prompt + generated[..|generated| - |currentConstrainedOut|];
  var next := helpers.ConstrainedStep(lm, parser, constrainedPrompt, currentConstrainedOut, eosToken);
  steps := steps + 1;
  innerSteps := innerSteps + 1;
  if next == eosToken {
    break;
  } else {
    var ag, ai, ac := helpers.AppendConstrainedToken(lm, parser, generated, currentConstrainedOut, next);
    generated := ag;
    insideConstrainedOut := ai;
    currentConstrainedOut := ac;
    innerTokenCount := innerTokenCount + 1;
  }
}

// Phase 3: If span still open, use CloseSpanWithinBudget
if insideConstrainedOut && steps < maxSteps {
  var remaining3 := maxSteps - steps;
  var spanBudget3: nat := remaining3;
  if spanBudget3 > 200 {
    spanBudget3 := 200;
  }
  if spanBudget3 > 0 {
    var wg, wi, wc := helpers.CloseSpanWithinBudget(lm, parser, prompt, generated, currentConstrainedOut, eosToken, spanBudget3);
    generated := wg;
    insideConstrainedOut := wi;
    currentConstrainedOut := wc;
    steps := steps + spanBudget3;
    if !insideConstrainedOut {
      hasCompletedSpan := true;
    }
  }
}

// Phase 4: If no span completed, continue free generation then force open span
while steps < phase1Limit && !insideConstrainedOut && !hasCompletedSpan
  invariant 0 <= steps <= maxSteps
  invariant lm.ValidTokensIdsLogits()
  invariant !insideConstrainedOut ==> currentConstrainedOut == []
  invariant insideConstrainedOut ==> parser.IsValidPrefix(currentConstrainedOut)
  invariant insideConstrainedOut ==> |currentConstrainedOut| <= |generated|
  invariant |generated| <= |generatedPrefix| + steps
  decreases phase1Limit - steps
{
  var next4 := helpers.UnconstrainedStep(lm, prompt, generated);
  steps := steps + 1;
  if next4 == eosToken {
    break;
  }
  generated := generated + [next4];
  if next4 == "<<" {
    var eg4, ei4, ec4 := helpers.EnterObservedConstrainedSpan(lm, generated);
    generated := eg4;
    insideConstrainedOut := ei4;
    currentConstrainedOut := ec4;
  }
}

// Phase 4b: constrained loop for second span entry
var innerSteps4: nat := 0;
var innerTokenCount4: nat := 0;

while insideConstrainedOut && !hasCompletedSpan && steps < maxSteps && innerSteps4 < innerStepLimit
  invariant 0 <= steps <= maxSteps
  invariant lm.ValidTokensIdsLogits()
  invariant !insideConstrainedOut ==> currentConstrainedOut == []
  invariant insideConstrainedOut ==> parser.IsValidPrefix(currentConstrainedOut)
  invariant insideConstrainedOut ==> |currentConstrainedOut| <= |generated|
  invariant |generated| <= |generatedPrefix| + steps
  decreases (maxSteps - steps) + (innerStepLimit - innerSteps4)
{
  if innerTokenCount4 >= minInnerTokens {
    var cg4, ci4, cc4, closed4 := helpers.CloseSpanIfComplete(lm, parser, generated, currentConstrainedOut);
    if closed4 {
      generated := cg4;
      insideConstrainedOut := ci4;
      currentConstrainedOut := cc4;
      steps := steps + 1;
      hasCompletedSpan := true;
      break;
    }
  }
  var constrainedPrompt4 := prompt + generated[..|generated| - |currentConstrainedOut|];
  var next4b := helpers.ConstrainedStep(lm, parser, constrainedPrompt4, currentConstrainedOut, eosToken);
  steps := steps + 1;
  innerSteps4 := innerSteps4 + 1;
  if next4b == eosToken {
    break;
  } else {
    var ag4, ai4, ac4 := helpers.AppendConstrainedToken(lm, parser, generated, currentConstrainedOut, next4b);
    generated := ag4;
    insideConstrainedOut := ai4;
    currentConstrainedOut := ac4;
    innerTokenCount4 := innerTokenCount4 + 1;
  }
}

// Phase 4c: CloseSpanWithinBudget for second span
if insideConstrainedOut && steps < maxSteps {
  var remaining4c := maxSteps - steps;
  var spanBudget4c: nat := remaining4c;
  if spanBudget4c > 150 {
    spanBudget4c := 150;
  }
  if spanBudget4c > 0 {
    var wg4c, wi4c, wc4c := helpers.CloseSpanWithinBudget(lm, parser, prompt, generated, currentConstrainedOut, eosToken, spanBudget4c);
    generated := wg4c;
    insideConstrainedOut := wi4c;
    currentConstrainedOut := wc4c;
    steps := steps + spanBudget4c;
    if !insideConstrainedOut {
      hasCompletedSpan := true;
    }
  }
}

// Phase 5: Force open span if still no completed span
if !insideConstrainedOut && !hasCompletedSpan && steps + 2 <= maxSteps {
  var fg, fi, fc := helpers.OpenConstrainedSpan(lm, generated);
  generated := fg;
  insideConstrainedOut := fi;
  currentConstrainedOut := fc;
  steps := steps + 1;

  var innerSteps5: nat := 0;
  var innerTokenCount5: nat := 0;
  var innerLimit5: nat := 80;

  while insideConstrainedOut && !hasCompletedSpan && steps < maxSteps && innerSteps5 < innerLimit5
    invariant 0 <= steps <= maxSteps
    invariant lm.ValidTokensIdsLogits()
    invariant !insideConstrainedOut ==> currentConstrainedOut == []
    invariant insideConstrainedOut ==> parser.IsValidPrefix(currentConstrainedOut)
    invariant insideConstrainedOut ==> |currentConstrainedOut| <= |generated|
    invariant |generated| <= |generatedPrefix| + steps
    decreases (maxSteps - steps) + (innerLimit5 - innerSteps5)
  {
    if innerTokenCount5 >= minInnerTokens {
      var cg5, ci5, cc5, closed5 := helpers.CloseSpanIfComplete(lm, parser, generated, currentConstrainedOut);
      if closed5 {
        generated := cg5;
        insideConstrainedOut := ci5;
        currentConstrainedOut := cc5;
        steps := steps + 1;
        hasCompletedSpan := true;
        break;
      }
    }
    var constrainedPrompt5 := prompt + generated[..|generated| - |currentConstrainedOut|];
    var next5 := helpers.ConstrainedStep(lm, parser, constrainedPrompt5, currentConstrainedOut, eosToken);
    steps := steps + 1;
    innerSteps5 := innerSteps5 + 1;
    if next5 == eosToken {
      break;
    } else {
      var ag5, ai5, ac5 := helpers.AppendConstrainedToken(lm, parser, generated, currentConstrainedOut, next5);
      generated := ag5;
      insideConstrainedOut := ai5;
      currentConstrainedOut := ac5;
      innerTokenCount5 := innerTokenCount5 + 1;
    }
  }

  if insideConstrainedOut && steps < maxSteps {
    var remainBudget5 := maxSteps - steps;
    if remainBudget5 > 60 {
      remainBudget5 := 60;
    }
    if remainBudget5 > 0 {
      var wg5, wi5, wc5 := helpers.CloseSpanWithinBudget(lm, parser, prompt, generated, currentConstrainedOut, eosToken, remainBudget5);
      generated := wg5;
      insideConstrainedOut := wi5;
      currentConstrainedOut := wc5;
      steps := steps + remainBudget5;
    }
  }
}

// Phase 6: Final safety - use ALL remaining budget to close
if insideConstrainedOut && steps < maxSteps {
  var finalBudget := maxSteps - steps;
  if finalBudget > 0 {
    var wgf, wif, wcf := helpers.CloseSpanWithinBudget(lm, parser, prompt, generated, currentConstrainedOut, eosToken, finalBudget);
    generated := wgf;
    insideConstrainedOut := wif;
    currentConstrainedOut := wcf;
    steps := steps + finalBudget;
  }
}

cost := steps;
