syncode: "<<" start ">>"

start: s_expr

csd_start: answer

answer: text_part* segment (text_part | segment)*

segment: "<<" start ">>"

text_part: TEXT
         | SINGLE_LT
         | SINGLE_GT

?n_expr: n_term
       | n_expr "+" n_term -> add
       | n_expr "-" n_term -> sub

?n_term: n_factor
       | n_term "*" n_factor -> mul
       | n_term "/" n_factor -> div
       | n_term "//" n_factor -> floordiv
       | n_term "%" n_factor -> mod

?n_factor: n_atom
         | "(" n_expr ")"

?n_atom: NUMBER
       | "int" "(" n_expr ")"

?s_expr: s_term
       | s_expr "+" n_term -> add
       | n_expr "+" s_term -> add
       | s_expr "+" s_term -> add
       | s_expr "-" n_term -> sub
       | n_expr "-" s_term -> sub
       | s_expr "-" s_term -> sub

?s_term: s_factor
       | s_term "*" n_factor -> mul
       | n_term "*" s_factor -> mul
       | s_term "*" s_factor -> mul
       | s_term "/" n_factor -> div
       | n_term "/" s_factor -> div
       | s_term "/" s_factor -> div
       | s_term "//" n_factor -> floordiv
       | n_term "//" s_factor -> floordiv
       | s_term "//" s_factor -> floordiv
       | s_term "%" n_factor -> mod
       | n_term "%" s_factor -> mod
       | s_term "%" s_factor -> mod

?s_factor: s_atom
         | "(" s_expr ")"

?s_atom: VARIABLE
       | VAR_LETTERS          -> var_letters
       | VAR_LETTERS NUMBER   -> var_num
       | VARIABLE NUMBER      -> var_num
       | "int" "(" s_expr ")"

VARIABLE: /[a-zA-Z_][a-zA-Z0-9_]*/
VAR_LETTERS: /[a-zA-Z_][a-zA-Z0-9_]*/
NUMBER: /-?\d+(\.\d+)?/

TEXT: /[^<>]+/
SINGLE_LT: "<"
SINGLE_GT: ">"

%import common.WS
%ignore WS
