// CSD_RATIONALE_BEGIN
// Root cause diagnosis of best approach (attempt 9/37, 49.7% accuracy, 93.7% syntax):
// The best approach closes the constrained span at the FIRST IsCompletePrefix occurrence.
// This causes premature closure in two key failure patterns observed in examples:
//
// 1. Multi-token table names: "SELECT people.birth_date FROM poker" is already a complete
//    SQL prefix if "poker" is a valid identifier, even though the correct table is
//    "poker_player". Early close at "FROM poker" prevents generating "_player".
//
// 2. Complex queries: "SELECT e.name FROM employee" is complete SQL, but the correct
//    answer requires "JOIN evaluation ON ... GROUP BY ... ORDER BY count(*) DESC LIMIT 1".
//    Early close misses these aggregation/join clauses entirely.
//
// Fix: Remove IsCompletePrefix early close from the generation loop. The model
// generates freely under GroupBoostedConstrainedStep(6.0) hard masking until EOS
// (natural completion signal) or sqlTokenCap=150 (repetition loop protection).
// Phase 4 uses CloseSpanWithinBudget which tracks the LONGEST complete prefix,
// allowing the full correct SQL to form before closure.
//
// This should help the model:
// - Extend "FROM poker" to "FROM poker_player" when schema boosting makes "_player" win
// - Generate "JOIN evaluation ON ... GROUP BY ..." after "FROM employee" naturally
//
// Other fixes vs best approach:
// 1. Replace forbidden `next == "<<"` with `RenderedEndsWith(generated, "<<")`.
// 2. Keep proven-best guidance string unchanged from attempt 9/37.
// 3. Keep same 5-step preamble, boost amount 6.0, and CloseSpanWithinBudget fallback.
// CSD_RATIONALE_END
// CSD_PROOF_SKETCH_BEGIN
// Invariant 1: parser_validity
//   insideConstrainedOut ==> parser.IsValidPrefix(currentConstrainedOut)
//
// Phase 1 (preamble loop):
//   Loop runs only when !insideConstrainedOut. If RenderedEndsWith detects "<<" after
//   appending next, we set currentConstrainedOut := [] which satisfies
//   parser.IsValidPrefix([]) by method precondition. Otherwise insideConstrainedOut
//   stays false (implication vacuously true). On EOS break, state is unchanged. ✓
//
// Phase 2 (OpenConstrainedSpan):
//   Only runs when !insideConstrainedOut. Sets insideConstrainedOut := true and
//   currentConstrainedOut := []. parser.IsValidPrefix([]) by method precondition. ✓
//
// Phase 3 (generation loop, no early close):
//   GroupBoostedConstrainedStep hard-masks to parser-valid tokens plus EOS.
//   Non-EOS path: AppendConstrainedToken extends currentConstrainedOut by the valid
//   token; by the parser's forward-validity contract, parser.IsValidPrefix still holds. ✓
//   EOS path: loop breaks, currentConstrainedOut unchanged, invariant preserved. ✓
//
// Phase 4 (close):
//   CloseConstrainedSpan: sets insideConstrainedOut := false and currentConstrainedOut
//   := [], making the implication vacuously true. ✓
//   CloseSpanWithinBudget: postcondition guarantees
//   insideOut ==> parser.IsValidPrefix(currentOut). ✓
//
// Invariant 2: progress
//   |generated| <= |generatedPrefix| + steps
//
// Phase 1: Each iteration increments steps by 1 and grows generated by at most 1
//   (0 on EOS break, 1 on non-EOS). ✓
// Phase 2: steps += 1, generated grows by exactly 1 ("<<"). ✓
// Phase 3: Each iteration increments steps by 1. On EOS break generated is unchanged;
//   on non-EOS AppendConstrainedToken grows generated by 1. Net per iteration:
//   steps +1, generated grows by at most 1. Invariant preserved. ✓
// Phase 4 (CloseConstrainedSpan): steps += 1, generated grows by at most 1 (">>").
//   |generated|_new <= (|generatedPrefix| + steps_old) + 1 = |generatedPrefix| + steps_new. ✓
// Phase 4 (CloseSpanWithinBudget): closeBudget = maxSteps - steps; postcondition
//   gives |generatedOut| <= |generated| + closeBudget. After steps := maxSteps:
//   |generatedOut| <= |generatedPrefix| + maxSteps = |generatedPrefix| + steps. ✓
// CSD_PROOF_SKETCH_END

generated := generatedPrefix;
insideConstrainedOut := insideConstrained;
currentConstrainedOut := currentConstrained;
cost := 0;

var guidance: string := "Output SQL: <<query>> where the query is a valid SQL SELECT statement using only the given schema tables and columns. Put your answer between << and >>. No explanation.";
helpers.AppendTaskGuidance(lm, guidance);

var steps: nat := 0;

// Phase 1: Short unconstrained preamble (at most 5 steps) to emit "SQL: " prefix
var preambleBudget: nat := 5;
var preambleSteps: nat := 0;

while steps < maxSteps && preambleSteps < preambleBudget && !insideConstrainedOut
  invariant 0 <= steps <= maxSteps
  invariant 0 <= preambleSteps <= preambleBudget
  invariant lm.ValidTokensIdsLogits()
  invariant !insideConstrainedOut ==> currentConstrainedOut == []
  invariant insideConstrainedOut ==> parser.IsValidPrefix(currentConstrainedOut)
  invariant insideConstrainedOut ==> |currentConstrainedOut| <= |generated|
  invariant |generated| <= |generatedPrefix| + steps
  decreases maxSteps - steps
{
  var next := helpers.UnconstrainedStep(lm, prompt, generated);
  steps := steps + 1;
  preambleSteps := preambleSteps + 1;
  if next == eosToken {
    break;
  } else {
    generated := generated + [next];
    if RenderedEndsWith(generated, "<<") {
      insideConstrainedOut := true;
      currentConstrainedOut := [];
    }
  }
}

// Phase 2: Force "<<" if not already inside constrained span
if !insideConstrainedOut && steps < maxSteps {
  var og, oi, oc := helpers.OpenConstrainedSpan(lm, generated);
  generated := og;
  insideConstrainedOut := oi;
  currentConstrainedOut := oc;
  steps := steps + 1;
}

// Phase 3: Generate SQL under hard constrained control WITHOUT early IsCompletePrefix close.
// Key change from best approach: model continues past first complete SQL prefix, enabling:
//   "FROM poker" -> continues to generate "_player" (completing "poker_player")
//   "FROM employee" -> continues with "JOIN evaluation ON ... GROUP BY ... ORDER BY ..."
// sqlTokenCap=150 prevents repetition loops from exhausting the step budget.
var sqlTokenCap: nat := 150;
while steps < maxSteps && insideConstrainedOut && |currentConstrainedOut| < sqlTokenCap
  invariant 0 <= steps <= maxSteps
  invariant lm.ValidTokensIdsLogits()
  invariant !insideConstrainedOut ==> currentConstrainedOut == []
  invariant insideConstrainedOut ==> parser.IsValidPrefix(currentConstrainedOut)
  invariant insideConstrainedOut ==> |currentConstrainedOut| <= |generated|
  invariant |generated| <= |generatedPrefix| + steps
  decreases maxSteps - steps
{
  var constrainedPrompt := prompt + generated[..|generated| - |currentConstrainedOut|];
  var next := helpers.GroupBoostedConstrainedStep(
    lm, parser, constrainedPrompt, currentConstrainedOut, validTokenGroups, 6.0, eosToken
  );
  steps := steps + 1;
  if next == eosToken {
    break;
  } else {
    var ag, ai, ac := helpers.AppendConstrainedToken(
      lm, parser, generated, currentConstrainedOut, next
    );
    generated := ag;
    insideConstrainedOut := ai;
    currentConstrainedOut := ac;
  }
}

// Phase 4: Close the constrained span.
// CloseConstrainedSpan when prefix is already complete (direct closure).
// CloseSpanWithinBudget otherwise: generates forward tracking the LONGEST complete
// prefix, then closes there. This handles both incomplete prefixes and cases where
// the model stopped mid-way through a complex SQL clause.
if insideConstrainedOut && steps < maxSteps {
  if parser.IsCompletePrefix(currentConstrainedOut) {
    var cg, ci, cc := helpers.CloseConstrainedSpan(
      lm, parser, generated, currentConstrainedOut
    );
    generated := cg;
    insideConstrainedOut := ci;
    currentConstrainedOut := cc;
    steps := steps + 1;
  } else {
    var closeBudget := maxSteps - steps;
    var cg, ci, cc := helpers.CloseSpanWithinBudget(
      lm, parser, prompt, generated, currentConstrainedOut, eosToken, closeBudget
    );
    generated := cg;
    insideConstrainedOut := ci;
    currentConstrainedOut := cc;
    steps := maxSteps;
  }
}

cost := steps;
